# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    working_directory: ~/repo

    environment:
      JAVA_TOOL_OPTIONS: -Xmx1024m

    steps:
    - checkout
    - run: docker run -e MYSQL_ALLOW_EMPTY_PASSWORD='yes' -e MYSQL_ROOT_PASSWORD='' -e MYSQL_DATABASE='CFBroker' -p 127.0.0.1:3306:3306/tcp -d circleci/mysql:5.7
    - run: docker run -p 127.0.0.1:8086:8086/tcp -d influxdb
    - run: docker-compose -f broker/src/functional-test/resources/credhub-docker-compose.yml up -d
    - run: 'if [[ -z "${CIRCLE_PULL_REQUEST}" ]]; then openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d; fi'
    - run: ./gradlew clean build -x functionalTest
    - run: ./circleci-publish.sh